apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: had-a-bad-day
    tier: challenge
  name: had-a-bad-day
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      labels:
        app: had-a-bad-day
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2020/had-a-bad-day
        name: had-a-bad-day
        ports:
        - containerPort: 80
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
      volumes: []
