apiVersion: v1
kind: Service
metadata:
  labels:
    app: had-a-bad-day
  name: had-a-bad-day
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: had-a-bad-day
  type: NodePort
