apiVersion: v1
kind: Service
metadata:
  labels:
    app: fun-with-flags
  name: fun-with-flags
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: fun-with-flags
  type: NodePort
