apiVersion: v1
kind: Service
metadata:
  labels:
    app: chameleon
  name: chameleon
spec:
  ports:
  - port: 4567
    protocol: TCP
    targetPort: 4567
  selector:
    app: chameleon
  type: NodePort
