apiVersion: v1
kind: Service
metadata:
  labels:
    app: eavesdropper
  name: eavesdropper
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: eavesdropper
  type: NodePort
