apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: csp-2
    tier: challenge
  name: csp-2
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      labels:
        app: csp-2
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2020/csp-2
        name: csp-2
        ports:
        - containerPort: 8000
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
      - env:
        - name: COOKIES
          value: admin=f9c56c41eb6896da26b49fbc8c03b4d0;URL=https://csp-2-2446d5a3.challenges.bsidessf.net/;httpOnly
        - name: PORT
          value: '3000'
        image: gcr.io/bsides-sf-ctf-2020/webbot:latest
        name: webbot
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
      volumes: []
