apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-todos
  name: simple-todos
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: simple-todos
  type: NodePort
