[package]
name = "config-me"
version = "0.1.0"
authors = ["iagox86 <ron-git@skullsecurity.org>"]
edition = "2018"

[profile.release]
opt-level = 3

[dependencies]
salsa20 = "0.3.0"
hex = "0.4.0"
simple-error = "0.1"
rand = "0.7.2"
