apiVersion: v1
kind: Service
metadata:
  labels:
    app: eccmul
  name: eccmul
spec:
  loadBalancerIP: 35.230.55.106
  ports:
  - port: 25519
    protocol: TCP
    targetPort: 25519
  selector:
    app: eccmul
  type: LoadBalancer
