apiVersion: v1
kind: Service
metadata:
  labels:
    app: ruler
  name: ruler
spec:
  loadBalancerIP: 35.185.209.53
  ports:
  - port: 4141
    protocol: TCP
    targetPort: 4141
  selector:
    app: ruler
  type: LoadBalancer
