apiVersion: v1
kind: Service
metadata:
  labels:
    app: webbleed
  name: webbleed
spec:
  loadBalancerIP: 104.199.124.95
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: webbleed
  type: LoadBalancer
