apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bulls23
    tier: challenge
  name: bulls23
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      labels:
        app: bulls23
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2020/bulls23
        name: bulls23
        ports:
        - containerPort: 8888
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
      volumes: []
